name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci
    - run: npm --prefix restapi ci
    - run: npm --prefix webapp test --coverage --watchAll
    - run: npm --prefix restapi test --coverage --watchAll
#    - run: npm --prefix webapp run test:e2e --coverage --watchAll
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
